export const ERROR_CODES = {
  AUTH: {
    INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
    ACCOUNT_INACTIVE: 'AUTH_ACCOUNT_INACTIVE',
    UNAUTHORIZED: 'AUTH_UNAUTHORIZED',
    FORBIDDEN: 'AUTH_FORBIDDEN',
  },
  PROFILE: {
    NOT_FOUND: 'PROFILE_NOT_FOUND',
  },
  SKILL: {
    NOT_FOUND: 'SKILL_NOT_FOUND',
  },
  EXPERIENCE: {
    NOT_FOUND: 'EXPERIENCE_NOT_FOUND',
  },
  PROJECT: {
    NOT_FOUND: 'PROJECT_NOT_FOUND',
    SLUG_EXISTS: 'PROJECT_SLUG_EXISTS',
  },
  BLOG: {
    NOT_FOUND: 'BLOG_NOT_FOUND',
    SLUG_EXISTS: 'BLOG_SLUG_EXISTS',
  },
  CONTACT: {
    NOT_FOUND: 'CONTACT_NOT_FOUND',
  },
  NEWSLETTER: {
    ALREADY_EXISTS: 'NEWSLETTER_ALREADY_EXISTS',
  },
  SETTINGS: {
    NOT_FOUND: 'SETTINGS_NOT_FOUND',
  },
  MEDIA: {
    NOT_FOUND: 'MEDIA_NOT_FOUND',
  },
  COMMON: {
    VALIDATION_FAILED: 'VALIDATION_FAILED',
    INTERNAL_ERROR: 'INTERNAL_ERROR',
    NOT_FOUND: 'NOT_FOUND',
  },
} as const;
